### PR TITLE
Refactor to MirageJS

### PR DESCRIPTION
**Pull request by minkimcello**
## Motivation
Screen Shot 2020-07-14 at 4 57 15 PM
This is part of an on-going initiative to completely migrate all of `folio-org` projects from `@bigtest/mirage` to `miragejs`.

[`@bigtest/mirage`](https://github.com/bigtestjs/mirage/) was originally a prototype to make `mirage` available to any framework, but it has since been archived in favor of [`miragejs`](https://miragejs.com/). The documentation for `miragejs` is not only prodigious for its extensive API docs but also for its tutorials and guides. Furthermore, it receives regular bug-fixes and maintenance releases in thanks to its extremely large and active community.

Previous PR: [@folio-org/ui-data-export #110](https://github.com/folio-org/ui-data-export/pull/110)
_Linking the previous pull request so that subsequent ones can be found tagged below._

<details>
<summary>Overview of progress at the time of the creation of this PR (in chronological order):</summary>
<br>
✅ <code>ui-checkin</code>
<br>
☑️ <code>ui-checkout</code>
<br>
☑️ <code>ui-circulation</code>
<br>
☑️ <code>ui-calendar</code>
<br>
☑️ <code>ui-agreements</code>
<br>
☑️ <code>ui-app-template</code>
<br>
☑️ <code>ui-inventory</code>
<br>
☑️ <code>ui-data-export</code>
<br>
☑️ <code>ui-finc-config</code>
</details>

## Approach
- [x] Cloned, installed, and then ran tests to double check that the tests are passing before refactoring.
- [x] Removed `@bigtest/mirage` and added `inflected`, `faker`, and `miragejs`.
- [x] Ran tests after the refactor to confirm they all pass.

### CODE REVIEW

**Comment by minkimcello** [comment]
@dltj I can't tag reviewers on this pull request for some reason.

**Comment by dltj** [comment]
@minkimcello : I'm not sure why—I see two reviewer suggestions @rchr and @elsenhans.  Is there someone else you want tagged?

**Comment by minkimcello** [comment]
@dltj who's the tech lead of `ui-finc-config`?

**Comment by rchr** [comment]
@minkimcello you can tag me as a reviewer. I am the tech lead of ui-finc-config. (And sorry for the late response!)

**Comment by minkimcello** [comment]
@rchr Could you tag yourself? I'm unable to tag anyone for review on this repository for some reason.

**Comment by rchr** [comment]
Sure! I tagged myself.

**Pull request merged**
